### CREATE QRCODE qrcode
POST http://localhost:3001/qrcode
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4YTI4Yzg3Mi03ZmQ5LTRhMTQtYjA5Ny05YWU3MDBhNGFmZTIiLCJlbWFpbCI6ImZpbGlwZS5zaXF1ZWlyYUBub3ZhbmV0LXJqLmNvbS5iciIsInR5cGVfdXNlciI6ImFkbWluIiwicGFzc3dvcmQiOiIkMmIkMTAkZC92Um9yaXA5NWxLaERJOERMTS9OZUFDdmo5RGVuTjU2ZEh0ZVY5eDVoL0lqaDRoVy9WZnkiLCJpYXQiOjE3NDkwMzY2ODEsImV4cCI6MTc0OTEyMzA4MX0.4eN6bi3A20LmnmCZSOBis7J9OU5iQaELnZdov3xzrbQ

{ 
  "name": "COMERCIAL ENTREVISTAS",
  "number_fone": "5521971211060",
  "link_add": ""
}

### FIND BY ID
GET http://localhost:3001/qrcode/3edf800c-5b62-4623-b429-5e953dfe9442
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4YTI4Yzg3Mi03ZmQ5LTRhMTQtYjA5Ny05YWU3MDBhNGFmZTIiLCJlbWFpbCI6ImZpbGlwZS5zaXF1ZWlyYUBub3ZhbmV0LXJqLmNvbS5iciIsInR5cGVfdXNlciI6ImFkbWluIiwicGFzc3dvcmQiOiIkMmIkMTAkZC92Um9yaXA5NWxLaERJOERMTS9OZUFDdmo5RGVuTjU2ZEh0ZVY5eDVoL0lqaDRoVy9WZnkiLCJpYXQiOjE3NDg1NDU3MDQsImV4cCI6MTc0ODYzMjEwNH0.otB98Wwh7bmOSodva5oECpcCRTV6vvggrtqGGDvUnS8

### FIND ALL
GET http://localhost:3001/qrcode
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4YTI4Yzg3Mi03ZmQ5LTRhMTQtYjA5Ny05YWU3MDBhNGFmZTIiLCJlbWFpbCI6ImZpbGlwZS5zaXF1ZWlyYUBub3ZhbmV0LXJqLmNvbS5iciIsInR5cGVfdXNlciI6ImFkbWluIiwicGFzc3dvcmQiOiIkMmIkMTAkZC92Um9yaXA5NWxLaERJOERMTS9OZUFDdmo5RGVuTjU2ZEh0ZVY5eDVoL0lqaDRoVy9WZnkiLCJpYXQiOjE3NDg1NDU3MDQsImV4cCI6MTc0ODYzMjEwNH0.otB98Wwh7bmOSodva5oECpcCRTV6vvggrtqGGDvUnS8

### DELETE
DELETE http://localhost:3000/qrcode/34d5f753-53bb-4f0d-95d1-08843736e161
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNGIzZmE4Yy05ZTg4LTQxZWMtYWQ3OS04ZTgyMzc4MGE0YmQiLCJlbWFpbCI6ImZpbGlwZS5zaXF1ZWlyYUBleGVtcGxvLmNvbSIsImlkX3VzZXIiOiIzYmJlMzczNi1jYmUwLTRiMDEtODY4Zi1jOGQ1NjYxMzk3ZWMiLCJ0eXBlX3VzZXIiOiJhZG1pbiIsImlhdCI6MTc0NTg0MDQxMywiZXhwIjoxNzQ1OTI2ODEzfQ.FoX7HdON4T_2U-ZTnlcgtAZjHnLk8ARv2LTCNu4Mq8I

### UPDATE
PATCH http://localhost:3001/qrcode/3edf800c-5b62-4623-b429-5e953dfe9442
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4YTI4Yzg3Mi03ZmQ5LTRhMTQtYjA5Ny05YWU3MDBhNGFmZTIiLCJlbWFpbCI6ImZpbGlwZS5zaXF1ZWlyYUBub3ZhbmV0LXJqLmNvbS5iciIsInR5cGVfdXNlciI6ImFkbWluIiwicGFzc3dvcmQiOiIkMmIkMTAkZC92Um9yaXA5NWxLaERJOERMTS9OZUFDdmo5RGVuTjU2ZEh0ZVY5eDVoL0lqaDRoVy9WZnkiLCJpYXQiOjE3NDg1NDU3MDQsImV4cCI6MTc0ODYzMjEwNH0.otB98Wwh7bmOSodva5oECpcCRTV6vvggrtqGGDvUnS8

{
  "name": "CRC ENTREVISTAS",
  "number_fone": 5521971211060,
  "link_add": "https://wa.me/5521971211060",
  "status": true
}