### CREATE USER
POST http://localhost:3001/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4YTI4Yzg3Mi03ZmQ5LTRhMTQtYjA5Ny05YWU3MDBhNGFmZTIiLCJlbWFpbCI6ImZpbGlwZS5zaXF1ZWlyYUBub3ZhbmV0LXJqLmNvbS5iciIsInR5cGVfdXNlciI6ImFkbWluIiwicGFzc3dvcmQiOiIkMmIkMTAkaDhhOVdmTk1aZ3BSNVo1emd1dUx4ZWlTSktpdnVTSXEuclZkTy91NC9XdEpDQ2E2T0NVRjYiLCJpYXQiOjE3NDc2NjE4OTUsImV4cCI6MTc0Nzc0ODI5NX0.sNsTGPi5F6QtbXeaAzprjY1GiqmrrNmaetWrN209KDc

{
  "email": "filipelobacksiqueira01@gmail.com",
  "name": "Filipe Loback",
  "password": "123456",
  "status": true,
  "type_user": "owner"
}

### FIND BY ID
GET http://localhost:3001/user/8a28c872-7fd9-4a14-b097-9ae700a4afe2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4YTI4Yzg3Mi03ZmQ5LTRhMTQtYjA5Ny05YWU3MDBhNGFmZTIiLCJlbWFpbCI6ImZpbGlwZS5zaXF1ZWlyYUBub3ZhbmV0LXJqLmNvbS5iciIsInR5cGVfdXNlciI6ImFkbWluIiwicGFzc3dvcmQiOiIkMmIkMTAkaDhhOVdmTk1aZ3BSNVo1emd1dUx4ZWlTSktpdnVTSXEuclZkTy91NC9XdEpDQ2E2T0NVRjYiLCJpYXQiOjE3NDc2NjE4OTUsImV4cCI6MTc0Nzc0ODI5NX0.sNsTGPi5F6QtbXeaAzprjY1GiqmrrNmaetWrN209KDc

### FIND ALL USER
GET  http://localhost:3001/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyY2MwYjBhNC1mZjY0LTQ0NGItYmUzZS01ODQ5MjQ3MTBmMjciLCJlbWFpbCI6ImZpbGlwZWxvYmFja3NpcXVlaXJhMDFAZ21haWwuY29tIiwidHlwZV91c2VyIjoidXNlciIsInBhc3N3b3JkIjoiJDJiJDEwJGZpSXIxS0lHcnNGemR3M05DbGpKLi5QRlBSb2N5Vzdpclk0NUpsL3pXR25DRHBuNURxOVdpIiwiaWF0IjoxNzUyNzAxNzk3LCJleHAiOjE3NTI3ODgxOTd9.lZnH5xzfQ0JSlcd2-BAKRpoT6K1goz_NWpzCwPz2czw

### UPDATE USER
PATCH http://localhost:3001/user/8a28c872-7fd9-4a14-b097-9ae700a4afe2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyY2MwYjBhNC1mZjY0LTQ0NGItYmUzZS01ODQ5MjQ3MTBmMjciLCJlbWFpbCI6ImZpbGlwZWxvYmFja3NpcXVlaXJhMDFAZ21haWwuY29tIiwidHlwZV91c2VyIjoidXNlciIsInBhc3N3b3JkIjoiJDJiJDEwJGZpSXIxS0lHcnNGemR3M05DbGpKLi5QRlBSb2N5Vzdpclk0NUpsL3pXR25DRHBuNURxOVdpIiwiaWF0IjoxNzUyNzAxNDA0LCJleHAiOjE3NTI3ODc4MDR9.Ea9OwKI99BLH12IBIluZhswDmt_ZPth5aKXVhXMtr40

{
  "email": "filipe.siqueira@novanet-rj.com.br",
  "name": "filipe siqueira",
  "password": "senha1234",
  "status": true,
  "type_user": "owner"
}

### DELETE USER
DELETE http://localhost:3000/user/0504936b-a3a8-409c-a56d-56fde4d3ce29
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNGIzZmE4Yy05ZTg4LTQxZWMtYWQ3OS04ZTgyMzc4MGE0YmQiLCJlbWFpbCI6ImZpbGlwZS5zaXF1ZWlyYUBleGVtcGxvLmNvbSIsImlkX3VzZXIiOiIzYmJlMzczNi1jYmUwLTRiMDEtODY4Zi1jOGQ1NjYxMzk3ZWMiLCJ0eXBlX3VzZXIiOiJhZG1pbiIsImlhdCI6MTc0NTg0MDQxMywiZXhwIjoxNzQ1OTI2ODEzfQ.FoX7HdON4T_2U-ZTnlcgtAZjHnLk8ARv2LTCNu4Mq8I