
### FIND ALL
GET http://localhost:3001/scan
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyY2MwYjBhNC1mZjY0LTQ0NGItYmUzZS01ODQ5MjQ3MTBmMjciLCJlbWFpbCI6ImZpbGlwZWxvYmFja3NpcXVlaXJhMDFAZ21haWwuY29tIiwidHlwZV91c2VyIjoidXNlciIsInBhc3N3b3JkIjoiJDJiJDEwJDRpVWpOS0FIM2FNUHNQN1lIMXFwdmVac1AwSGVtWmp1aDFQbXM4V3pIR25RVU1MQmU5eTdxIiwiaWF0IjoxNzUxMTUyNDUyLCJleHAiOjE3NTEyMzg4NTJ9.iLWyKklbab9WJuN4HwltiXvMZAmy1ZeEmXB4dljHDOw

### FIND ID
GET http://localhost:3000/scan/find/2a29deba-8922-434b-a0a0-61a36ffd2dbc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyY2MwYjBhNC1mZjY0LTQ0NGItYmUzZS01ODQ5MjQ3MTBmMjciLCJlbWFpbCI6ImZpbGlwZWxvYmFja3NpcXVlaXJhMDFAZ21haWwuY29tIiwidHlwZV91c2VyIjoidXNlciIsInBhc3N3b3JkIjoiJDJiJDEwJDRpVWpOS0FIM2FNUHNQN1lIMXFwdmVac1AwSGVtWmp1aDFQbXM4V3pIR25RVU1MQmU5eTdxIiwiaWF0IjoxNzUxMTUyNDUyLCJleHAiOjE3NTEyMzg4NTJ9.iLWyKklbab9WJuN4HwltiXvMZAmy1ZeEmXB4dljHDOw


### Delete
DELETE http://localhost:3000/scan/c68ffd6c-710d-47a0-bf61-8053bf5af62e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNGIzZmE4Yy05ZTg4LTQxZWMtYWQ3OS04ZTgyMzc4MGE0YmQiLCJlbWFpbCI6ImZpbGlwZS5zaXF1ZWlyYUBleGVtcGxvLmNvbSIsImlkX3VzZXIiOiIzYmJlMzczNi1jYmUwLTRiMDEtODY4Zi1jOGQ1NjYxMzk3ZWMiLCJ0eXBlX3VzZXIiOiJhZG1pbiIsImlhdCI6MTc0NTk0OTM0MiwiZXhwIjoxNzQ2MDM1NzQyfQ.zm4Ep6TVuIgGrHrucRA4trnN7a6x6ghGX9RFYmU8cwg 

### findAllJoin
GET http://localhost:3001/scan/join
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4YTI4Yzg3Mi03ZmQ5LTRhMTQtYjA5Ny05YWU3MDBhNGFmZTIiLCJlbWFpbCI6ImZpbGlwZS5zaXF1ZWlyYUBub3ZhbmV0LXJqLmNvbS5iciIsInR5cGVfdXNlciI6ImFkbWluIiwicGFzc3dvcmQiOiIkMmIkMTAkZC92Um9yaXA5NWxLaERJOERMTS9OZUFDdmo5RGVuTjU2ZEh0ZVY5eDVoL0lqaDRoVy9WZnkiLCJpYXQiOjE3NDc4MzAwNjUsImV4cCI6MTc0NzkxNjQ2NX0.0taoL0_SCcuRWndvsw1DljgcrG5D8ODi6q0W3hmhX6c
