
### FIND ALL
GET http://localhost:3000/scan/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNGIzZmE4Yy05ZTg4LTQxZWMtYWQ3OS04ZTgyMzc4MGE0YmQiLCJlbWFpbCI6ImZpbGlwZS5zaXF1ZWlyYUBleGVtcGxvLmNvbSIsImlkX3VzZXIiOiIzYmJlMzczNi1jYmUwLTRiMDEtODY4Zi1jOGQ1NjYxMzk3ZWMiLCJ0eXBlX3VzZXIiOiJhZG1pbiIsImlhdCI6MTc0NTk0OTM0MiwiZXhwIjoxNzQ2MDM1NzQyfQ.zm4Ep6TVuIgGrHrucRA4trnN7a6x6ghGX9RFYmU8cwg 

### FIND ID
GET http://localhost:3000/scan/find/2a29deba-8922-434b-a0a0-61a36ffd2dbc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNGIzZmE4Yy05ZTg4LTQxZWMtYWQ3OS04ZTgyMzc4MGE0YmQiLCJlbWFpbCI6ImZpbGlwZS5zaXF1ZWlyYUBleGVtcGxvLmNvbSIsImlkX3VzZXIiOiIzYmJlMzczNi1jYmUwLTRiMDEtODY4Zi1jOGQ1NjYxMzk3ZWMiLCJ0eXBlX3VzZXIiOiJhZG1pbiIsImlhdCI6MTc0NTk0OTM0MiwiZXhwIjoxNzQ2MDM1NzQyfQ.zm4Ep6TVuIgGrHrucRA4trnN7a6x6ghGX9RFYmU8cwg 


### Delete
DELETE http://localhost:3000/scan/c68ffd6c-710d-47a0-bf61-8053bf5af62e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNGIzZmE4Yy05ZTg4LTQxZWMtYWQ3OS04ZTgyMzc4MGE0YmQiLCJlbWFpbCI6ImZpbGlwZS5zaXF1ZWlyYUBleGVtcGxvLmNvbSIsImlkX3VzZXIiOiIzYmJlMzczNi1jYmUwLTRiMDEtODY4Zi1jOGQ1NjYxMzk3ZWMiLCJ0eXBlX3VzZXIiOiJhZG1pbiIsImlhdCI6MTc0NTk0OTM0MiwiZXhwIjoxNzQ2MDM1NzQyfQ.zm4Ep6TVuIgGrHrucRA4trnN7a6x6ghGX9RFYmU8cwg 


